import type { Dict } from "./tr";

export const en: Dict = {
  meta: {
    title: "Startup Doktoru — Free Startup Training and Fundraising Guide",
    description:
      "Startup training built on a real pitch deck that raised. Start with the free 12-minute training, then continue with the ebook and video courses. 10 years in the field.",
    ogLocale: "en_US",
  },

  pageMeta: {
    ebook: {
      title: "Startup Ebook: 13 Chapters from MVP to Valuation | Startup Doktoru",
      description:
        "Innovation, MVP, product-market fit, team building, cash flow, company valuation and investor negotiation — a 13-chapter startup book. The English edition is in preparation; sign up to be notified.",
    },
    egitimler: {
      title: "Startup Video Courses — 3 Courses, One Bundle | Startup Doktoru",
      description:
        "Pitch deck preparation, the startup founding guide and company valuation. $70 each, or all three together in a single $99 bundle.",
    },
    freeTraining: {
      title: "Free Startup Training — 12-Minute Video | Startup Doktoru",
      description:
        "The fundamentals of building a startup in 12 minutes: real innovation, MVP, and the first signals investors look for. Free video training, just sign up.",
    },
    investorTraining: {
      title: "How to Pitch Investors? Video Course | Startup Doktoru",
      description:
        "Slide-by-slide pitch deck training built on a real deck that raised. 5 modules, 134 minutes. The 12 critical mistakes that make investors say no on the spot.",
    },
    degerleme: {
      title: "How to Value a Startup? Berkus & DCF | Startup Doktoru",
      description:
        "Company valuation with the Berkus, scorecard, risk factor and DCF methods — and how to walk into an investor negotiation from a position of strength.",
    },
    startupGiris: {
      title: "How to Start a Startup? Founding Guide Course | Startup Doktoru",
      description:
        "Real innovation, escaping over-engineering, brand positioning, MVP development, team building and competitor analysis — the whole setup in one course.",
    },
    blog: {
      title: "Startup Blog — Entrepreneurship and Fundraising | Startup Doktoru",
      description:
        "Actionable writing on entrepreneurship, fundraising, company valuation and growth. News and field notes from the startup world.",
    },
  },

  nav: {
    problem: "The Problem",
    solution: "Our Solution",
    ebook: "Ebook",
    training: "Courses",
    blog: "Blog",
    about: "About",
  },

  header: {
    homeAria: "Startup Doktoru home",
    aiMentor: "AI Mentor",
    myPanel: "My Dashboard",
    login: "Log in",
    memberLogin: "Member Login",
    buyEbook: "Get the Ebook",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    logout: "Log out",
    switchLanguage: "Change language",
  },

  footer: {
    rights: "© 2026 Startup Doktoru. All rights reserved. \u201CA caravan isn\u2019t sorted out on the road — it\u2019s sorted out with strategy.\u201D",
    copyright: "© 2026 Startup Doktoru. All rights reserved.",
    trainings: "Courses",
    freeTraining: "Free Training",
    blog: "Blog",
    privacy: "Privacy Policy",
    distanceSales: "Distance Sales Agreement",
    terms: "Terms of Use",
  },

  home: {
    hero: {
      badge: "10 Years in Startups and Venture Funding",
      titleLead: "The target:",
      titleHighlight: "A Million Dollars",
      subtitle:
        "Ten years of hard-won experience, distilled into a step-by-step path for building a million-dollar startup.",
      ctaFree: "Start the Free Training",
      riskReducer: "No credit card · access in 2 minutes",
      ebookLink: "or take a look at the book →",
      stats: [
        { value: "100+", label: "Founders Mentored" },
        { value: "3", label: "Companies Founded" },
        { value: "10+ Years", label: "In the Field" },
      ],
    },

    problem: {
      eyebrow: "The Core Problems",
      title: "Why Do Founders Fail?",
      lead: "Four operational truths behind months of work going to waste:",
      items: [
        {
          title: "Chasing the Wrong Metrics",
          desc: "Tracking likes and vanity growth numbers instead of real revenue and real users.",
        },
        {
          title: "A Weak Pitch Deck",
          desc: "Building a 50-slide deck that never answers the five questions actually on an investor's mind.",
        },
        {
          title: "Over-Engineering",
          desc: "Spending months coding features the market never validated, and delaying launch again and again.",
        },
        {
          title: "Growth Without a System",
          desc: "Running the business into chaos with no KPIs, no task ownership and no real delegation.",
        },
      ],
    },

    ladder: {
      eyebrow: "A Journey Built on Trust",
      title: "The Startup Value Ladder",
      lead: "We do not sell high-ticket offers up front. We earn your trust one step at a time:",
      popular: "Most Popular",
      discountBadge: "50% off",
      steps: [
        {
          step: "Step 01",
          title: "Free Training",
          desc: "Shows you the most costly mistakes founders make in front of investors — and delivers value immediately.",
          price: "Free",
          oldPrice: "",
          btnText: "Sign Up",
        },
        {
          step: "Step 02",
          title: "Ebook",
          desc: "The practical handbook for building a million-dollar startup in 13 critical steps.",
          price: "Coming soon",
          oldPrice: "",
          btnText: "Get Notified",
        },
        {
          step: "Step 03",
          title: "Video Courses",
          desc: "Pitch deck preparation, the startup founding guide and company valuation. 50% off each if you own the ebook.",
          price: "$70 / bundle $99",
          oldPrice: "",
          btnText: "See the Courses",
        },
      ],
    },

    ebookSection: {
      eyebrow: "The Digital Transformation Handbook",
      title: "Hedef Milyon Dolar",
      body: "This book distills ten years of innovation, fundraising and growth experience. Step by step, with real examples, it shows you how to build the backbone of your company.",
      chapters: [
        "01. Innovation & a Useful Idea",
        "02. Over-Engineering (the Engineer's Disease)",
        "03. Going to Market with an MVP",
        "04. Problem Validation & Product-Market Fit",
        "05. Brand Positioning & Competitor Analysis",
        "06. Building a Team (CEO, COO, CFO)",
        "07. Cash Flow Management",
        "08. Company Valuation (Berkus, Scorecard, DCF)",
        "09. Angel Investors & Negotiation",
        "10. The Investor Pitch",
      ],
      cta: "English Edition — Notify Me",
      cardTag: "The System Book",
    },

    trainingSection: {
      eyebrow: "Video Course · Most Requested",
      title: "How Do You Pitch Investors?",
      bodyBefore: "Not theory — we work ",
      bodyStrong: "through a real deck that actually raised",
      bodyAfter: ". I open the slides one by one and show you what convinces an investor. The one-minute preview is free.",
      videoTitle: "Pitch Deck Course — Preview",
      videoLabel: "Watch the one-minute preview",
      posterBadge: "Free Preview",
      posterTitle: "How Do You Pitch Investors?",
      posterSubtitle: "Built on a real deck that raised",
      modules: [
        "Problem & Solution Narrative",
        "Market Size & Competitor Analysis",
        "Building a Team & Investor Confidence",
        "Business Model & Revenue Logic",
        "Teardown of a Deck That Raised",
      ],
      cta: "Watch the Preview & Get Access",
      note: "Preview is free · Full course $70 ($35 if you own the ebook)",
    },

    about: {
      eyebrow: "About Startup Doktoru",
      name: "Eser Memişoğlu",
      p1: "For the past ten years I have worked across startups, technology, innovation and investor relations. I have founded three technology companies and walked alongside dozens of founders and scale-up brands as they built their operating systems.",
      p2: "I am against running a business on improvisation. With Startup Doktoru I have turned my hardest-won lessons into products, so you can turn your business model into an autonomous system that is fundable and scales profitably.",
      stats: [
        { value: "10+", label: "Years of Experience" },
        { value: "3", label: "Companies Founded" },
        { value: "100+", label: "Founders Mentored" },
      ],
      portraitAlt: "Eser Memişoğlu — Founder & Startup Advisor",
      role: "Founder & Startup Advisor",
      roleNote: "Working on innovation, financing, investor relations and growth systems.",
      quote: "A caravan isn't sorted out on the road — it's sorted out with strategy.",
      quoteCaption: "Eser Memişoğlu's principle",
    },

    faqSection: {
      eyebrow: "Common Questions",
      title: "Frequently Asked Questions",
      items: [
        {
          q: "What exactly is Startup Doktoru?",
          a: "Startup Doktoru is a training, mentoring and growth platform that turns the founder's journey — from idea to funding — into a system. The goal is not theory: it is helping you build business models and growth funnels you can actually run.",
        },
        {
          q: "How do I get the ebook after buying it?",
          a: "The moment your purchase goes through, the PDF download link appears on screen. An access link to the student portal is also sent automatically to the email address you signed up with.",
        },
        {
          q: "What will the pitch deck course do for me?",
          a: "The course breaks down the five things investors look for in a deck: metrics, team, problem-solution, market size and the financial roadmap. By the end you will have built a deck professional enough to convince investors.",
        },
        {
          q: "How can I get one-on-one advisory?",
          a: "Our advisory model follows the value ladder. Once you have taken the free training or picked up the ebook, you can request a Startup Check-Up or Growth Advisory directly from your dashboard or the contact form.",
        },
      ],
    },

    finalCta: {
      badge: "The Automated Growth Machine",
      title: "Ready to turn your startup into a fundable, profitable system?",
      body: "Don't stop at theory. Take your business up a level today with Startup Doktoru's practical handbooks, video course modules and automated growth playbooks.",
      primary: "Start the Free Training",
      secondary: "English Edition — Notify Me",
    },

    stickyBar: {
      title: "Hedef Milyon Dolar",
      meta: "English edition coming",
      cta: "Notify Me",
    },
  },

  prices: {
    ebookOld: "$12",
    ebookNew: "$6",
  },

  testimonials: {
    eyebrow: "Student Results",
    title: "What Do Graduates Say?",
    lead: "From real founders, in their own words.",
    watch: "Watch",
    videoTitleSuffix: "testimonial",
  },

  vcNetwork: {
    eyebrow: "A Credible Source",
  },

  discountPopup: {
    normalPrice: "Regular price",
    todayForYou: "Today, for you",
    discountBadge: "50% off · Grab it now",
    close: "Close",
    title: "Wait — before you go!",
    bodyStrong: "Hedef Milyon Dolar",
    bodyRest: " — get the ebook at half price on your first order.",
    emailPlaceholder: "your email address",
    cta: "Get It for $6",
    noSpam: "No spam. Unsubscribe whenever you like.",
    doneTitle: "Your discount is ready 🎉",
    doneBody: "You can download the ebook at half price right now.",
    doneCta: "Get It for $6",
  },

  ebookPage: {
    backHome: "Home",
    badge: "The Million-Dollar Startup Guide",
    title: "Hedef Milyon Dolar",
    intro:
      "Ten years of founding startups, innovation work and investment management, distilled into a single book. Turn your company from a pile of chaos into a profitable growth machine that runs itself.",
    features: [
      "Innovation and over-engineering: avoid the mistakes that sink startups",
      "Company valuation: the Berkus, Scorecard and DCF methods",
      "Finding angel investors and negotiating with them",
      "What actually works in a pitch deck that raised",
    ],
    discountBadge: "50% off",
    cta: "Get It Now for $6",
    cardTag: "PDF Edition",
    chaptersEyebrow: "Contents",
    chaptersTitle: "Chapters and Curriculum",
    chaptersLead: "The 13 chapters we go through in depth — and that you apply in your own company:",
    chapters: [
      { t: "What Is Innovation? The Formula for Getting It Right", d: "Not a 'new idea' but a 'useful idea': what innovation really means, and the formula that strengthens a startup idea." },
      { t: "Over-Engineering: The Engineer's Disease", d: "How shipping features nobody asked for sinks a startup — and how to break the habit." },
      { t: "What Is an MVP? Launching With the Least", d: "Getting to market with the fastest, cheapest MVP without falling into the perfectionism trap." },
      { t: "Problem Validation & Product-Market Fit", d: "Finding the problem customers actually pay to solve, and reaching product-market fit." },
      { t: "Brand Positioning & Competitor Analysis", d: "Deciding how people see you, and claiming the right position through competitor analysis." },
      { t: "Building a Startup Team: CEO, COO, CFO", d: "C-level roles, filling the gaps with the right people, and hiring at the right time." },
      { t: "Cash Flow Management: The Mistake That Kills", d: "'Cash flow kills' — where startups go under most often, and how to keep the financial model standing." },
      { t: "What Is Company Valuation? Which Method, When", d: "Know your own value before you walk into an investor meeting: valuation is context, not fantasy." },
      { t: "Valuation With the Berkus Method", d: "Angel investor Dave Berkus's valuation method for pre-revenue startups." },
      { t: "The Scorecard Valuation Method", d: "Weighing quantitative and qualitative criteria together with the scorecard method." },
      { t: "Valuation With DCF and Risk Factors", d: "A realistic valuation using discounted cash flow and risk-factor adjustment." },
      { t: "Angel Investors & Negotiating the Deal", d: "Who angel investors are, how rounds work, and the tactics that keep you strong at the table." },
      { t: "The Investor Pitch: A Million Dollars in 4 Minutes", d: "What convinces an investor, walked through a real deck that raised." },
    ],
    checkoutNote: "Instant PDF download access",
  },

  checkout: {
    title: "Secure Checkout",
    close: "Close",
    preparing: "Getting your details ready…",
    nameLabel: "Full Name",
    namePlaceholder: "Jane Doe",
    emailLabel: "Email Address",
    emailPlaceholder: "jane@startup.com",
    phoneLabel: "Phone Number",
    phoneOptional: "(optional)",
    phonePlaceholder: "+1 555 000 0000",
    preparingBtn: "Preparing...",
    toPayment: "Continue to Payment",
    ssl: "Secure payment with 256-bit SSL encryption (Stripe).",
    verifying: "Verifying payment...",
    complete: "Complete Payment",
    errorPayment: "The payment could not be completed. Please try again.",
    errorStart: "The payment could not be started.",
    errorConnection: "Connection error. Please try again.",
  },

  video: {
    comingSoon: "Video coming soon",
  },

  auth: {
    titleLogin: "Student Portal",
    titleSignup: "Create an Account",
    titleForgot: "Reset Password",
    subLogin: "Log in to your account.",
    subSignup: "Get to your courses and your ebook from here.",
    subForgot: "Enter your email and we'll send a reset link.",
    google: "Continue with Google",
    orEmail: "or with email",
    namePlaceholder: "Full name",
    emailPlaceholder: "Your email address",
    phonePlaceholder: "Phone (+1 555 000 0000)",
    phoneHint: "Your phone number is needed so investors can reach you.",
    passwordPlaceholder: "Password",
    btnLogin: "Log In",
    btnSignup: "Sign Up",
    btnForgot: "Send Link",
    noAccount: "Don't have an account?",
    signupLink: "Sign up",
    forgotLink: "I forgot my password",
    haveAccount: "Already have an account?",
    loginLink: "Log in",
    backToLogin: "← Back to login",
    errBadCredentials: "Wrong email or password.",
    errLoginFailed: "Login failed.",
    errShortPassword: "Password must be at least 6 characters.",
    errAlreadyRegistered: "This email is already registered. Log in instead.",
    errSignupFailed: "Sign-up failed.",
    infoConfirm: "You're registered! Click the confirmation link in your email, then log in.",
    errGeneric: "Something went wrong.",
    infoResetSent: "A password reset link has been sent to your email.",
  },

  phonePrompt: {
    doneTitle: "Thank you! 🎉",
    doneBody: "You've been added to our investor network.",
    title: "One last step 📞",
    bodyBefore: "Leaving your phone number ",
    bodyStrong1: "matters",
    bodyMiddle: " — it's how investors ",
    bodyStrong2: "get in touch with you",
    bodyAfter: ". Our team reaches out when a suitable opportunity comes up.",
    placeholder: "+1 555 000 0000",
    save: "Save My Number",
    dismiss: "Not now",
  },

  trainingPage: {
    allTrainings: "All Courses",
    badge: "{n}-Part Video Course",
    start: "Start the Course (${price})",
    startNow: "Start the Course Now (${price})",
    ebookDiscount: "${price} if you own the ebook",
    ebookDiscountNote: "50% off with the $6 ebook →",
    bundle: "All courses ${price}",
    bundleNote: "All three courses in one bundle →",
    previewSuffix: "Preview",
    watchPreview: "Watch the Preview",
    previewNote: "Preview is free · Full course {n} parts, ${price} (${discount} if you own the ebook)",
    curriculumEyebrow: "Curriculum",
    curriculumTitle: "What's Inside",
    curriculumLead: "{n} video parts — practical, with examples from the field.",
    ebook: "Ebook",
    checkoutNote: "{n} parts · lifetime access",
  },

  trainingsPage: {
    eyebrow: "Courses",
    title: "Video Courses for Every Step of the Fundraising Journey",
    lead: "Pick them one by one, or get all of them in the bundle. Every course is practical, full of examples from the field.",
    discountAppliedBefore: "Your ebook discount is applied — every single course is now ",
    discountAppliedStrong: "50% off ($35)",
    discountAppliedAfter: ". Pick one below.",
    ebookNudgeBefore: "Anyone who buys the $6 ebook gets every course at ",
    ebookNudgeStrong: "50% off ($35)",
    ebookNudgeAfter: " →",
    slideBonus: "Every course comes with the full slide deck I teach from.",
    bestValue: "Best Value",
    bundleOldPrice: "$210",
    bundleNote: "All three courses",
    bundleCta: "Get the Bundle (${price})",
    previewSuffix: "Preview",
    watchPreview: "Watch the Preview",
    buy: "Buy",
    noteDiscounted: "Video course · 50% off for ebook owners",
    noteNormal: "Video course · lifetime access",
    details: "See the course details →",
    unsureNudge: "Not sure yet? Start with the free training.",
    freeCta: "Join the Free 12-Minute Training",
  },

  investorTrainingPage: {
    badge: "5-Module Video Course",
    titleTop: "Building an Investor",
    titleBottom: "Pitch Deck",
    intro:
      "90% of investor meetings are lost in the first four minutes. In this video course you learn, step by step, the five things investors look for in a pitch — and how to prepare each one.",
    features: [
      "134 minutes of content across 5 dedicated modules",
      "A real pitch deck teardown and reusable slide templates",
      "The 12 mistakes that make investors say no on the spot",
      "Valuation methodologies and the TAM/SAM/SOM formulas",
    ],
    start: "Start the Course ($70)",
    startNow: "Start the Course Now ($70)",
    videoTitle: "Pitch Deck Course — Preview",
    previewNote: "Preview is free · Full course 5 modules, $70 ($35 if you own the ebook)",
    curriculumEyebrow: "Curriculum",
    curriculumTitle: "Investor-Ready in 5 Modules",
    curriculumLead: "Every module carries concrete examples from real investor meetings, plus templates you can use directly.",
    modulePrefix: "Module",
    modules: [
      {
        title: "What Investors Expect & the Right Metrics",
        desc: "The five questions running through an investor's mind during a pitch — and a systematic way to prepare for each of them.",
        duration: "28 min",
      },
      {
        title: "Framing the Problem & Presenting the Solution",
        desc: "How to tell the story of a painful problem and your systematic solution in a way that is built around how investors think.",
        duration: "35 min",
      },
      {
        title: "Competitor Analysis & Positioning Strategy",
        desc: "The positioning-map method for building the strongest possible answer to the question investors always ask: why you?",
        duration: "22 min",
      },
      {
        title: "The Team Story & Building Trust",
        desc: "The three qualities investors look for in a team, and a storytelling frame that proves your team has them.",
        duration: "18 min",
      },
      {
        title: "Critical Mistakes & Deck Optimization",
        desc: "The most common deck mistakes collected from real investor meetings, with slide-by-slide fixes that remove them.",
        duration: "31 min",
      },
    ],
    checkoutTitle: "Investor Pitch Deck Course",
    checkoutNote: "5 modules · 134 minutes, full access",
  },

  freeTrainingPage: {
    badge: "Free Video Training",
    titleTop: "The 7 Fatal Mistakes Startups Make",
    titleBottom: "In Front of Investors",
    intro:
      "90% of investor meetings are lost in the first four minutes. In this practical session you learn, with real examples, the mistakes Eser Memişoğlu has collected over ten years — the ones that get an instant no.",
    features: [
      "The biggest structural mistakes in pitch slides",
      "How to size your market correctly (TAM, SAM, SOM)",
      "The financial growth language investors want to hear",
      "AI integration and scaling-strategy promises",
    ],
    formTitle: "Join the Training Now",
    formLead: "Just fill in the form below to watch the training.",
    namePlaceholder: "Your Full Name",
    emailPlaceholder: "Your Email Address",
    phonePlaceholder: "Your Phone Number (WhatsApp)",
    companyPlaceholder: "Company / Project Name",
    stages: {
      idea: "Idea stage",
      mvp: "Prototype / MVP",
      preSeed: "First sales (Pre-Seed)",
      seed: "Preparing to raise (Seed)",
      growth: "Scaling (Growth)",
    },
    consent: "I agree to receive training links, weekly growth tips and WhatsApp updates.",
    submitting: "Saving...",
    submit: "Unlock the Training",
    accessGranted: "Access Granted",
    videoHeading: "The 7 Fatal Mistakes Startups Make in Front of Investors",
    videoTitle: "The Free 12-Minute Startup Training",
    videoLabel: "Start the Training (12 Minutes)",
    posterBadge: "Free · 12 Minutes",
    posterTitle: "The 7 Fatal Mistakes Made in Front of Investors",
    posterSubtitle: "Click to watch — no credit card needed",
    upsellEyebrow: "THE NEXT STEP",
    upsellTitle: "Unlock everything it takes to build a million-dollar startup",
    upsellBodyBefore: "Get ",
    upsellBodyStrong: "Hedef Milyon Dolar",
    upsellBodyAfter: " — covering check-ups, MVP development, funnel setup and growth automation.",
    upsellCta: "Get the Ebook ($6)",
  },

  thankYouPage: {
    loading: "Loading...",
    badge: "Payment Successful",
    titleEbook: "Your Ebook Is Ready!",
    titleCourse: "Your Access Is Open!",
    bodyEbook:
      "Your copy of Hedef Milyon Dolar has been purchased. You can start downloading below — the link has also been sent to your email address.",
    bodyCourse:
      "You now have full access to the course you purchased. Log in to the student portal to start watching.",
    ctaEbook: "Download the Ebook",
    ctaCourse: "Start the Course",
    upsellEyebrow: "You've Unlocked 50% Off",
    upsellTitle: "Get the Courses at Your Special Price",
    upsellBodyBefore: "Because you bought the ebook, every video course is ",
    upsellBodyStrong: "50% off",
    upsellBodyAfter: " for you. Two options:",
    option1: "Option 1 · Pick one course",
    option2: "Option 2 · All of them — best value",
    bundleNote: "All three courses",
    bundleCta: "${price} · Get Them All",
    bundleOldPrice: "$210",
    noteDiscounted: "Video course · 50% off for ebook owners",
    consultEyebrow: "Work With Us One-on-One",
    consultTitleTop: "Build Your Growth Plan",
    consultTitleBottom: "With a Startup Check-Up",
    consultBodyBefore: "For founders who complete the course: register your interest in a one-on-one ",
    consultBodyStrong: "Startup Check-Up and Growth Advisory",
    consultBodyAfter: " session with Eser Memişoğlu.",
    consultCta: "Register Free",
  },

  portal: {
    notLoggedIn: "Not logged in",
    student: "Student",
    navCourse: "Course Content",
    navEbook: "My Files",
    backHome: "Back to Home",
    logout: "Log Out",

    myTrainings: "My Courses",
    dashboardEyebrow: "My Learning Dashboard",
    welcome: "Welcome 👋",
    freeBadge: "Free",
    freeCardTitle: "The Free 12-Minute Training",
    freeCardDesc: "The 7 fatal mistakes made in front of investors.",
    watch: "Watch",
    freeEyebrow: "Free Training",
    freeHeading: "The 7 Fatal Mistakes Made in Front of Investors",
    freeVideoTitle: "The Free 12-Minute Training",
    freeVideoLabel: "Start the Training (12 Minutes)",
    freePosterBadge: "Free · 12 Minutes",
    previewSuffix: "Preview",
    watchPreview: "Watch the Preview",
    completed: "Completed",
    markCompleted: "Mark as completed",
    sections: "Parts",
    progress: "Progress",
    continue: "Continue",
    startWatching: "Start Watching",
    ebookCardTitle: "My Files",
    ebookCardDesc: "Your book and course slides live here.",
    otherTrainings: "Other Courses",
    trainings: "Courses",
    preview: "Preview",
    buy: "Buy",
    discountNote: "Ebook owners get 50% off every course (${price}).",

    owned: "Owned",
    read: "Read",
    withEbook: "/ ${price} with the ebook",
    belgeKitap: "The Book (digital edition)",
    belgeKitapLead: "The digital edition of the printed book — read it right here on the site.",
    belgeSunum: "Course Slides",
    belgeSunumLead: "The full slide deck I teach from in the courses.",
    belgeHazirlaniyor: "This document is being prepared and will be here shortly.",
    belgelerBaslik: "My Files",
    ebookEmptyTitle: "Your ebook will appear here",
    ebookEmptyBodyBefore: "We found no ebook purchase for this email. You can get Hedef Milyon Dolar for ",
    ebookEmptyBodyAfter: ".",
    ebookEmptyCta: "Get the Ebook ($6)",
    ebookTitle: "Hedef Milyon Dolar",
    ebookLead: "You can read your book right here on the site.",
    ebookFooter: "Access is tied to your account — come back and read any time.",
    ebookError: "The ebook could not be opened.",
    connectionError: "Connection error.",
  },

  ai: {
    greeting:
      "Hi! I'm the Startup Doktoru AI mentor. I can help you validate your idea, get ready for a valuation, or build growth funnels.\n\nWhat are you working on? Tell me about your idea in a couple of lines and we'll take it apart together.",
    title: "AI Mentor Assistant",
    subtitle: "Eser Memişoğlu's Growth & Fundraising Model",
    close: "Close",
    gateTitle: "Before we connect you",
    gateLead:
      "A few quick details so I can answer for you and your project specifically. They're used only to help you better.",
    namePlaceholder: "Your full name",
    emailPlaceholder: "Your email address",
    phonePlaceholder: "Phone (+1 555 000 0000)",
    projectPlaceholder: "Project name (real or a placeholder)",
    gateCta: "Start Talking to the Mentor",
    gateNote: "Your details stay confidential and are never shared with third parties.",
    statusBefore: "Current status:",
    statusValue: "Startup Check-Up pending",
    raiseScore: "Raise Score",
    roleUser: "Founder",
    roleAssistant: "Dr. Startup AI",
    thinking: "Analyzing the idea and mapping the growth funnel...",
    inputPlaceholder: "Describe your startup or what you're stuck on...",
    fallbackIntro: "Your idea ('{snippet}...') is a good one. \n\nTrying to grow before you build a system is the biggest mistake there is. Here are the first three critical steps for turning this idea into a company:\n\n1. **Problem validation:** Talk to 10 potential customers and test whether this problem is genuinely painful for them.\n2. **MVP development:** Strip out every unnecessary feature and build the simplest version that still delivers the core promise.\n3. **The value ladder:** Instead of going straight for the big sale, earn trust first with something free or small (like the $6 ebook).\n\nYou'll find detailed guides for each step in the ebook or the course portal. Happy to keep answering questions!",
    disclaimer:
      "Guidance from the Startup Doktoru AI mentor is not investment advice. \u201CA caravan isn't sorted out on the road — it's sorted out with strategy.\u201D",
  },

  blog: {
    eyebrow: "Blog",
    title: "Writing on Building Startups",
    lead: "Practical pieces from the field on fundraising, valuation, innovation and growth.",
    empty: "No posts published yet. Coming soon.",
    read: "Read",
    back: "All posts",
    notFound: "Post not found — Startup Doktoru",
    draftPrefix: "[DRAFT]",
    draftNoticeStrong: "Draft preview.",
    draftNoticeBefore: " This post is not published — visitors cannot see it and search engines are blocked. Use the ",
    draftNoticeEm: "Publish",
    draftNoticeAfter: " button in the admin panel to take it live.",
    ctaLead: "Ready to take your startup up a level?",
    cta: "See the Ebook ($6)",
    dateLocale: "en-US",
  },

  ebookEn: {
    badge: "English Edition",
    title: "The English edition is on its way",
    lead: "The book is currently available in Turkish only. We're preparing the English edition — leave your email and you'll be the first to know.",
    placeholder: "your email address",
    cta: "Notify Me",
    sending: "Sending...",
    doneTitle: "You're on the list",
    doneBody: "We'll write to you the moment the English edition is out. In the meantime, the free training is worth a look.",
    error: "That didn't go through — mind trying again?",
    turkishNote: "Read Turkish? You can get the book right now.",
    turkishCta: "Go to the Turkish edition",
  },
};
