// Türkçe metin sözlüğü — kaynak dil. Yeni metin önce buraya, sonra en.ts'e eklenir;
// en.ts bu dosyanın tipine bağlı olduğu için eksik çeviri derlemede hata verir.

export const tr = {
  meta: {
    // Ana sayfanın başlığı. "yatırımcı sunumu nasıl yapılır" sorgusu /investor-training
    // sayfasına bırakıldı; sayfalar aynı sorguda birbiriyle yarışmasın.
    title: "Startup Doktoru — Ücretsiz Startup Eğitimi ve Yatırım Rehberi",
    description:
      "Yatırım almış gerçek bir sunum üzerinden startup eğitimi. 12 dakikalık ücretsiz eğitimle başlayın; e-kitap ve video eğitimlerle devam edin. 10 yıllık saha tecrübesi.",
    ogLocale: "tr_TR",
  },

  // Her sayfanın kendi başlık/açıklaması — arama motorunda ayrı sonuç olarak çıkar.
  pageMeta: {
    ebook: {
      title: "Startup E-Kitabı: MVP'den Değerlemeye 13 Bölüm | Startup Doktoru",
      description:
        "İnovasyon, MVP, ürün-pazar uyumu, ekip kurma, nakit akışı, şirket değerleme ve yatırımcı pazarlığı — 13 bölümlük startup e-kitabı, 6 dolar.",
    },
    egitimler: {
      title: "Startup Video Eğitimleri — 3 Eğitim, Tek Paket | Startup Doktoru",
      description:
        "Yatırımcı sunumu hazırlama, startup giriş rehberi ve şirket değerleme eğitimleri. Tek tek 70 dolar, üçü birden 99 dolarlık tek pakette.",
    },
    freeTraining: {
      title: "Ücretsiz Startup Eğitimi — 12 Dakikalık Video | Startup Doktoru",
      description:
        "12 dakikada startup kurmanın temelleri: doğru inovasyon, MVP ve yatırımcının aradığı ilk sinyaller. Ücretsiz video eğitimi, kayıt olmanız yeterli.",
    },
    investorTraining: {
      title: "Yatırımcı Sunumu Nasıl Yapılır? Video Eğitim | Startup Doktoru",
      description:
        "Yatırım almış gerçek bir pitch deck üzerinden slayt slayt yatırımcı sunumu hazırlama eğitimi. 5 modül, 134 dakika. Yatırımcıların anında 'hayır' dediği 12 kritik hata.",
    },
    degerleme: {
      title: "Startup Değerleme Nasıl Yapılır? Berkus & DCF | Startup Doktoru",
      description:
        "Berkus, puan kartı, risk faktörleri ve DCF yöntemleriyle şirket değerleme; yatırımcıyla pazarlıkta masaya güçlü oturmanın yolları. Video eğitim.",
    },
    startupGiris: {
      title: "Startup Nasıl Kurulur? Giriş Rehberi Eğitimi | Startup Doktoru",
      description:
        "Doğru inovasyon, over-engineering'den kurtulma, marka konumlandırma, MVP geliştirme, ekip kurma ve rakip analizi — startup kurulumunun tamamı tek eğitimde.",
    },
    blog: {
      title: "Startup Blogu — Girişimcilik ve Yatırım | Startup Doktoru",
      description:
        "Girişimcilik, yatırım, şirket değerleme ve büyüme üzerine uygulanabilir yazılar. Startup dünyasından haberler ve saha notları.",
    },
  },
  nav: {
    problem: "Problem",
    solution: "Çözümümüz",
    ebook: "E-Kitap",
    training: "Eğitimler",
    blog: "Blog",
    about: "Hakkında",
  },

  header: {
    homeAria: "Startup Doktoru ana sayfa",
    aiMentor: "AI Mentor",
    myPanel: "Panelim",
    login: "Giriş",
    memberLogin: "Üye Girişi",
    buyEbook: "E-Kitap Al",
    openMenu: "Menüyü aç",
    closeMenu: "Menüyü kapat",
    logout: "Çıkış Yap",
    switchLanguage: "Dili değiştir",
  },

  footer: {
    rights: "© 2026 Startup Doktoru. Tüm Hakları Saklıdır. \u201CKervan yolda değil, stratejiyle düzülür.\u201D",
    copyright: "© 2026 Startup Doktoru. Tüm Hakları Saklıdır.",
    trainings: "Eğitimler",
    freeTraining: "Ücretsiz Eğitim",
    blog: "Blog",
    privacy: "Gizlilik Politikası",
    distanceSales: "Mesafeli Satış Sözleşmesi",
    terms: "Kullanım Şartları",
  },
  home: {
    hero: {
      badge: "10 Yıllık Startup ve Yatırım Tecrübesi",
      titleLead: "Hedef:",
      titleHighlight: "Milyon Dolar",
      subtitle:
        "10 yıllık bilgi birikimiyle, nasıl milyon dolarlık bir girişim kurulur — adım adım anlatıyorum.",
      ctaFree: "Ücretsiz Eğitime Katıl",
      riskReducer: "Kredi kartı gerekmez · 2 dakikada erişim",
      ebookLink: "ya da e-kitabı incele ·",
      stats: [
        { value: "100+", label: "Girişimci Mentorluk" },
        { value: "3", label: "Girişim Kurulumu" },
        { value: "10+ Yıl", label: "Saha Tecrübesi" },
      ],
    },

    problem: {
      eyebrow: "Temel Sorunlar",
      title: "Girişimciler Neden Başarısız Oluyor?",
      lead: "Aylarca süren emeklerin heba olmasının ardındaki 4 ölümcül operasyonel gerçek:",
      items: [
        {
          title: "Yanlış Metrik Odaklılık",
          desc: "Gerçek ciro ve kullanıcı yerine sadece 'beğeni' ve sahte büyüme rakamlarını takip etmek.",
        },
        {
          title: "Yetersiz Yatırımcı Sunumu",
          desc: "Yatırımcının zihnindeki kritik 5 soruyu es geçerek 50 slaytlık sıkıcı sunumlar hazırlamak.",
        },
        {
          title: "Over-Engineering",
          desc: "Pazarın doğrulamadığı özellikler için aylarca kod yazıp pazara çıkışı ertelemek.",
        },
        {
          title: "Sistemsiz Büyüme",
          desc: "KPI, görev yönetimi ve doğru delegasyon kurmadan işin kendisini kaosa sürüklemek.",
        },
      ],
    },

    ladder: {
      eyebrow: "Güven Temelli Yolculuk",
      title: "Startup Değer Merdiveni",
      lead: "Platformumuzda doğrudan yüksek bütçeli satışlar yapmayız. Sizinle güven bağımızı adım adım büyütürüz:",
      popular: "En Popüler",
      discountBadge: "%50 indirim",
      steps: [
        {
          step: "Adım 01",
          title: "Ücretsiz Eğitim",
          desc: "Yatırımcıların karşısında yapılan en kritik hataları gösterip anında değer üretir.",
          price: "Ücretsiz",
          oldPrice: "",
          btnText: "Kayıt Ol",
        },
        {
          step: "Adım 02",
          title: "E-Kitap",
          desc: "13 kritik adımda milyon dolarlık bir startup kurmanın pratik el kitabını edinirsiniz.",
          price: "6 USD",
          oldPrice: "12 $",
          btnText: "Hemen 6 $'a Al",
        },
        {
          step: "Adım 03",
          title: "Video Eğitimler",
          desc: "Yatırımcı sunumu, startup giriş rehberi ve değerleme eğitimleri. E-kitap alana her biri %50 indirimli.",
          price: "70 $ / paket 99 $",
          oldPrice: "",
          btnText: "Eğitimleri Gör",
        },
      ],
    },

    ebookSection: {
      eyebrow: "Dijital Dönüşüm El Kitabı",
      title: "Hedef Milyon Dolar",
      body: "Bu kitap, son 10 yılda edindiğimiz inovasyon, yatırımcılık ve büyüme tecrübelerinin damıtılmış bir özetidir. Adım adım şirketinizin omurgasını nasıl kuracağınızı örneklerle öğretir.",
      chapters: [
        "01. İnovasyon & Faydalı Fikir",
        "02. Over-Engineering (Mühendis Hastalığı)",
        "03. MVP ile Pazara Çıkış",
        "04. Problem Doğrulama & Ürün-Pazar Uyumu",
        "05. Marka Konumlandırma & Rakip Analizi",
        "06. Ekip Kurma (CEO, COO, CFO)",
        "07. Nakit Akışı Yönetimi",
        "08. Şirket Değerleme (Berkus, Scorecard, DCF)",
        "09. Melek Yatırımcı & Pazarlık",
        "10. Yatırımcı Sunumu (Pitch)",
      ],
      cta: "E-Kitabı İndir (6 $)",
      cardTag: "Sistem Kitabı",
    },

    trainingSection: {
      eyebrow: "Video Eğitim · En Çok Aranan",
      title: "Yatırımcı Sunumu Nasıl Yapılır?",
      bodyBefore: "Teoriyle değil, ",
      bodyStrong: "gerçekten yatırım almış bir sunum üzerinden",
      bodyAfter: " ilerliyoruz. Slaytları tek tek açıp yatırımcıyı ikna eden püf noktalarını gösteriyorum. 1 dakikalık önizleme ücretsiz.",
      videoTitle: "Yatırımcı Sunumu Eğitimi — Önizleme",
      videoLabel: "1 dakikalık önizlemeyi izle",
      posterBadge: "Ücretsiz Önizleme",
      posterTitle: "Yatırımcı Sunumu Nasıl Yapılır?",
      posterSubtitle: "Yatırım almış gerçek bir sunum üzerinden",
      modules: [
        "Problem & Çözüm Anlatımı",
        "Pazar Büyüklüğü & Rakip Analizi",
        "Ekip Kurma & Yatırımcıya Güven",
        "İş Modeli & Gelir Mantığı",
        "Yatırım Almış Gerçek Sunum İncelemesi",
      ],
      cta: "Önizlemeyi İzle & Eğitime Eriş",
      note: "Tanıtım ücretsiz · Tam eğitim 70 $ (e-kitap alana 35 $)",
    },

    about: {
      eyebrow: "Startup Doktoru Hakkında",
      name: "Eser Memişoğlu",
      p1: "Son 10 yıldır startup, teknoloji, inovasyon ve yatırım ilişkileri alanlarında aktif rol oynamaktayım. Bugüne kadar 3 farklı teknoloji şirketinin kuruculuğunu üstlendim, onlarca girişimciye ve scale-up markaya sistem kurulumu konusunda yol arkadaşlığı yaptım.",
      p2: "İşlerin plansız ve 'kervan yolda düzülür' diyerek yürütülmesine karşıyım. Startup Doktoru platformu ile edindiğim en kritik dersleri ürünleştirerek, iş modelinizi yatırım alabilecek ve kârlı bir şekilde ölçeklenebilecek otonom bir sisteme dönüştürmeyi hedefliyorum.",
      stats: [
        { value: "10+", label: "Yıl Tecrübe" },
        { value: "3", label: "Girişim Kurulumu" },
        { value: "100+", label: "Girişimci Mentorluk" },
      ],
      portraitAlt: "Eser Memişoğlu — Kurucu & Girişim Danışmanı",
      role: "Kurucu & Girişim Danışmanı",
      roleNote: "İnovasyon, Finansman, Yatırımcı İlişkileri ve Growth Sistemleri üzerine çalışmalarına devam ediyor.",
      quote: "Kervan yolda değil, stratejiyle düzülür.",
      quoteCaption: "Eser Memişoğlu'nun ilkesi",
    },

    faqSection: {
      eyebrow: "Merak Edilenler",
      title: "Sıkça Sorulan Sorular",
      items: [
        {
          q: "Startup Doktoru tam olarak nedir?",
          a: "Startup Doktoru, girişimcilerin fikir aşamasından yatırım aşamasına kadar olan yolculuğunu sistematik hale getiren bir eğitim, mentörlük ve büyüme platformudur. Amacımız sadece teorik bilgi değil, uygulanabilir iş modelleri ve büyüme hunileri kurmanızı sağlamaktır.",
        },
        {
          q: "E-Kitabı satın aldıktan sonra nasıl erişeceğim?",
          a: "E-Kitap satın alma işlemi tamamlandığında, anında dijital PDF indirme bağlantınız ekranda belirecektir. Ayrıca kayıt olduğunuz e-posta adresinize de otomatik olarak öğrenci portalı erişim linkiniz iletilecektir.",
        },
        {
          q: "Yatırımcı Sunumu Eğitimi bana ne kazandırır?",
          a: "Bu eğitim, yatırımcıların bir sunumda (pitch deck) aradığı 5 temel odağı (Metrikler, Ekip, Problem-Çözüm, Pazar Büyüklüğü ve Finansal Yol Haritası) detaylandırır. Eğitimi tamamladığınızda yatırımcıları ikna edebilecek seviyede profesyonel bir sunum hazırlamış olursunuz.",
        },
        {
          q: "Birebir danışmanlık hizmetini nasıl alabilirim?",
          a: "Danışmanlık modelimiz 'Değer Merdiveni' prensibine dayanır. Ücretsiz eğitim veya e-kitabımızı edindikten sonra panelimizden veya iletişim formundan doğrudan Startup Check-Up ve Growth Danışmanlığı talebi gönderebilirsiniz.",
        },
      ],
    },

    finalCta: {
      badge: "Otomatik Büyüme Makinesi",
      title: "Girişiminizi yatırım alınabilir, kârlı bir sisteme dönüştürmeye hazır mısınız?",
      body: "Teoride kalmayın. Startup Doktoru'nun pratik el kitapları, video eğitim modülleri ve otomatik büyüme stratejileri ile bugün işinizi bir üst kademeye taşıyın.",
      primary: "Ücretsiz Eğitime Başla",
      secondary: "E-Kitabı Edin (6 $)",
    },

    stickyBar: {
      title: "Hedef Milyon Dolar",
      meta: "E-Kitap ·",
      cta: "Hemen Al · 6 $",
    },
  },
  prices: {
    ebookOld: "12 $",
    ebookNew: "6 $",
  },

  testimonials: {
    eyebrow: "Öğrenci Sonuçları",
    title: "Eğitimi Alanlar Ne Diyor?",
    lead: "Gerçek girişimcilerden, kendi ağızlarından.",
    watch: "İzle",
    videoTitleSuffix: "memnuniyet",
  },

  vcNetwork: {
    eyebrow: "Güvenilir Kaynak",
  },

  discountPopup: {
    normalPrice: "Normal fiyat",
    todayForYou: "Bugün sana",
    discountBadge: "%50 İndirim · Hemen Yakala",
    close: "Kapat",
    title: "Gitmeden önce dur!",
    bodyStrong: "Hedef Milyon Dolar",
    bodyRest: " e-kitabını ilk siparişe özel yarı fiyatına al.",
    emailPlaceholder: "e-posta adresin",
    cta: "Hemen 6 $'a Al",
    noSpam: "Spam yok. İstediğin zaman çıkabilirsin.",
    doneTitle: "İndirimin hazır 🎉",
    doneBody: "E-kitabı şimdi yarı fiyatına, hemen indirebilirsin.",
    doneCta: "Hemen 6 $'a Sahip Ol",
  },
  ebookPage: {
    backHome: "Ana Sayfa",
    badge: "Milyon Dolarlık Startup Rehberi",
    title: "Hedef Milyon Dolar",
    intro:
      "10 yıllık startup kuruculuğu, inovasyon ve yatırım yönetimi tecrübesinin damıtılmış tek kitabı. Girişiminizi bir 'kaos yığını' olmaktan çıkarıp, otomatik işleyen kârlı bir büyüme makinesine dönüştürün.",
    features: [
      "İnovasyon ve over-engineering: startup'ı batıran hataları önle",
      "Şirket değerleme: Berkus, Puan Kartı (Scorecard) ve DCF yöntemleri",
      "Melek yatırımcı bulma ve yatırımcıyla pazarlık taktikleri",
      "Yatırım almış gerçek bir yatırımcı sunumunun püf noktaları",
    ],
    discountBadge: "%50 indirim",
    cta: "Hemen 6 $'a Sahip Ol",
    cardTag: "PDF Sürüm",
    chaptersEyebrow: "İçindekiler",
    chaptersTitle: "Kitap Bölümleri ve Müfredat",
    chaptersLead: "Kitap boyunca derinlemesine inceleyeceğimiz ve girişiminizde uygulayacağınız 13 bölüm:",
    chapters: [
      { t: "İnovasyon Nedir? Doğru İnovasyonun Formülü", d: "'Yeni fikir' değil 'faydalı fikir': inovasyonun gerçek tanımı ve startup fikrini güçlendiren formül." },
      { t: "Over-Engineering: Mühendis Hastalığı", d: "Kullanıcının istemediği özellikleri eklemeye devam etmek startup'ı nasıl batırır — ve aşırı mühendislikten kurtulma." },
      { t: "MVP Nedir? En Az Özellikle Pazara Çıkmak", d: "Mükemmeliyetçilik tuzağına düşmeden, en hızlı ve en ucuz MVP ile pazara çıkma." },
      { t: "Problem Doğrulama & Ürün-Pazar Uyumu", d: "Müşterinin gerçekten para ödediği problemi bulmak ve ürün-pazar uyumunu (product-market fit) yakalamak." },
      { t: "Marka Konumlandırma & Rakip Analizi", d: "İnsanların sizi nasıl gördüğünü belirlemek ve rakip analiziyle pazarda doğru yeri almak." },
      { t: "Startup'ta Ekip Kurma: CEO, COO, CFO", d: "C-level rolleri, ekipteki boşlukları doğru kişilerle doldurmak ve doğru zamanda işe almak." },
      { t: "Nakit Akışı Yönetimi: Startup'ı Öldüren Hata", d: "'Nakit akışı öldürür' — startup'ların en çok battığı yer ve finansal modeli ayakta tutma." },
      { t: "Şirket Değerleme Nedir? Hangi Yöntem Ne Zaman", d: "Yatırımcıya gitmeden önce şirketinin değerini kendin bil: değerleme bir hayal değil, bağlam işi." },
      { t: "Berkus Yöntemi ile Değerleme", d: "Geliri olmayan (pre-revenue) startup'lar için melek yatırımcı Dave Berkus'un değerleme yöntemi." },
      { t: "Puan Kartı (Scorecard) Değerleme Yöntemi", d: "Startup değerlemesinde puan kartı yöntemiyle nicel ve nitel kriterleri birlikte değerlendirmek." },
      { t: "DCF ve Risk Faktörleri ile Değerleme", d: "İndirgenmiş Nakit Akışı (DCF) ve risk faktörü düzeltmesiyle gerçekçi değerleme hesabı." },
      { t: "Melek Yatırımcı & Yatırımcıyla Pazarlık", d: "Melek yatırımcı kimdir, yatırım turları ve masada güçlü oturmanın pazarlık taktikleri." },
      { t: "Yatırımcı Sunumu: 4 Dakikada Milyon Dolar", d: "Yatırım almış gerçek bir sunum üzerinden, yatırımcıyı ikna eden pitch'in püf noktaları." },
    ],
    checkoutNote: "Anında PDF İndirme Erişimi",
  },
  checkout: {
    title: "Güvenli Ödeme",
    close: "Kapat",
    preparing: "Bilgilerin hazırlanıyor…",
    nameLabel: "Adınız Soyadınız",
    namePlaceholder: "Eser Memişoğlu",
    emailLabel: "E-posta Adresiniz",
    emailPlaceholder: "eser@girisim.com",
    phoneLabel: "Telefon Numaranız",
    phoneOptional: "(opsiyonel)",
    phonePlaceholder: "+90 5xx xxx xx xx",
    preparingBtn: "Hazırlanıyor...",
    toPayment: "Ödemeye Geç",
    ssl: "256-bit SSL şifreli güvenli ödeme (Stripe).",
    verifying: "Ödeme Doğrulanıyor...",
    complete: "Ödemeyi Tamamla",
    errorPayment: "Ödeme tamamlanamadı. Lütfen tekrar deneyin.",
    errorStart: "Ödeme başlatılamadı.",
    errorConnection: "Bağlantı hatası. Lütfen tekrar deneyin.",
  },
  video: {
    comingSoon: "Video yakında",
  },

  auth: {
    titleLogin: "Öğrenci Portalı",
    titleSignup: "Hesap Oluştur",
    titleForgot: "Şifre Sıfırla",
    subLogin: "Hesabınla giriş yap.",
    subSignup: "Eğitimlerine ve e-kitabına buradan ulaş.",
    subForgot: "E-postanı gir, sıfırlama bağlantısı gönderelim.",
    google: "Google ile devam et",
    orEmail: "veya e-posta ile",
    namePlaceholder: "Ad Soyad",
    emailPlaceholder: "E-posta adresin",
    phonePlaceholder: "Telefon (+90 5xx xxx xx xx)",
    phoneHint: "Yatırımcıların seninle iletişime geçebilmesi için telefonun gerekli.",
    passwordPlaceholder: "Şifre",
    btnLogin: "Giriş Yap",
    btnSignup: "Kayıt Ol",
    btnForgot: "Bağlantı Gönder",
    noAccount: "Hesabın yok mu?",
    signupLink: "Kayıt ol",
    forgotLink: "Şifremi unuttum",
    haveAccount: "Zaten hesabın var mı?",
    loginLink: "Giriş yap",
    backToLogin: "← Girişe dön",
    errBadCredentials: "E-posta veya şifre hatalı.",
    errLoginFailed: "Giriş başarısız.",
    errShortPassword: "Şifre en az 6 karakter olmalı.",
    errAlreadyRegistered: "Bu e-posta zaten kayıtlı. Giriş yap.",
    errSignupFailed: "Kayıt başarısız.",
    infoConfirm: "Kaydın alındı! E-postana gelen doğrulama bağlantısına tıkla, sonra giriş yap.",
    errGeneric: "İşlem başarısız.",
    infoResetSent: "Şifre sıfırlama bağlantısı e-postana gönderildi.",
  },

  phonePrompt: {
    doneTitle: "Teşekkürler! 🎉",
    doneBody: "Yatırımcı ağımıza eklendin.",
    title: "Son bir adım kaldı 📞",
    bodyBefore: "Yatırımcıların ",
    bodyStrong1: "seninle iletişime geçebilmesi",
    bodyMiddle: " için telefon numaranı bırakman ",
    bodyStrong2: "önemlidir",
    bodyAfter: ". Uygun yatırım fırsatlarında ekibimiz sana ulaşır.",
    placeholder: "+90 5xx xxx xx xx",
    save: "Numaramı Kaydet",
    dismiss: "Şimdi değil",
  },
  trainingPage: {
    allTrainings: "Tüm Eğitimler",
    badge: "{n} Bölüm Video Eğitim",
    start: "Eğitime Başla ({price} USD)",
    startNow: "Eğitime Hemen Başla ({price} USD)",
    ebookDiscount: "E-kitap alana {price} $",
    ebookDiscountNote: "6 $'lık e-kitapla %50 indirim →",
    bundle: "Tüm eğitimler {price} $",
    bundleNote: "3 eğitimin tamamı, tek pakette →",
    previewSuffix: "Tanıtım",
    watchPreview: "Tanıtımı İzle",
    previewNote: "Önizleme ücretsiz · Tam eğitim {n} bölüm, {price} $ (e-kitap alana {discount} $)",
    curriculumEyebrow: "Müfredat",
    curriculumTitle: "Eğitim İçeriği",
    curriculumLead: "{n} bölüm video — uygulanabilir, sahadan örneklerle.",
    ebook: "E-Kitap",
    checkoutNote: "{n} bölüm · ömür boyu erişim",
  },
  trainingsPage: {
    eyebrow: "Eğitimler",
    title: "Yatırım Yolculuğunun Her Adımı İçin Video Eğitimler",
    lead: "Tek tek seç ya da paketle hepsine sahip ol. Her eğitim uygulanabilir, sahadan örneklerle dolu.",
    discountAppliedBefore: "E-kitap indirimin uygulandı — tüm tek eğitimler ",
    discountAppliedStrong: "%50 indirimli (35 $)",
    discountAppliedAfter: ". Aşağıdan seç.",
    ebookNudgeBefore: "6 $'lık e-kitabı alan herkes tüm eğitimleri ",
    ebookNudgeStrong: "%50 indirimle (35 $)",
    ebookNudgeAfter: " alır →",
    slideBonus: "Her eğitimin yanında, derste anlattığım sunum dosyalarının tamamı hediye.",
    bestValue: "En Avantajlı",
    bundleOldPrice: "210 $",
    bundleNote: "3 eğitimin tamamı",
    bundleCta: "Paketi Al ({price} $)",
    previewSuffix: "Tanıtım",
    watchPreview: "Tanıtımı İzle",
    buy: "Satın Al",
    noteDiscounted: "Video eğitim · e-kitap alana özel %50",
    noteNormal: "Video eğitim · ömür boyu erişim",
    details: "Eğitim detaylarını incele →",
    unsureNudge: "Henüz emin değil misin? Önce ücretsiz eğitimle başla.",
    freeCta: "12 Dakikalık Ücretsiz Eğitime Katıl",
  },
  investorTrainingPage: {
    badge: "5 Modül Video Eğitim Paketi",
    titleTop: "Yatırımcı Sunumu",
    titleBottom: "Hazırlama Eğitimi",
    intro:
      "Yatırım görüşmelerinin %90'ı ilk 4 dakikada kaybedilir. Bu video eğitimde, yatırımcıların pitch'lerde aradığı 5 kritik bileşeni ve bunları nasıl hazırlayacağınızı adım adım öğreneceksiniz.",
    features: [
      "134 dakika toplam içerik, 5 özel modül",
      "Gerçek pitch deck analizi ve örnek sunum şablonları",
      "Yatırımcıların anında 'Hayır' dediği 12 kritik hata listesi",
      "Değerleme hesaplama metodolojileri ve TAM/SAM/SOM formülleri",
    ],
    start: "Eğitime Başla (70 USD)",
    startNow: "Eğitime Hemen Başla (70 USD)",
    videoTitle: "Yatırımcı Sunumu Eğitimi — Tanıtım",
    previewNote: "Önizleme ücretsiz · Tam eğitim 5 modül, 70 $ (e-kitap alana 35 $)",
    curriculumEyebrow: "Müfredat",
    curriculumTitle: "5 Modülde Yatırımcı Hazırlığı",
    curriculumLead: "Her modül, gerçek pitch görüşmelerinden derlenen somut örnekler ve uygulanabilir şablonlar içerir.",
    modulePrefix: "Modül",
    modules: [
      {
        title: "Yatırımcı Beklentileri & Doğru Metrikler",
        desc: "Bir yatırımcının pitch görüşmesinde zihninde döndürdüğü 5 kritik soruyu ve bu soruları hazırlamanın sistematik yolunu öğrenirsiniz.",
        duration: "28 dk",
      },
      {
        title: "Problem Anlatımı & Çözüm Sunumu",
        desc: "Yatırımcı psikolojisine göre tasarlanmış, acı veren problemi ve şirketinizin sunduğu sistematik çözümü ikna edici şekilde nasıl anlatırsınız.",
        duration: "35 dk",
      },
      {
        title: "Rakip Analizi & Konumlandırma Stratejisi",
        desc: "Yatırımcıların 'Neden Siz?' sorusuna verecekleri yanıtı en güçlü şekilde kurgulamanın konumlandırma haritası metodunu öğrenmek.",
        duration: "22 dk",
      },
      {
        title: "Ekip Hikayesi & Güven Kurulumu",
        desc: "Yatırımcının bir ekipte aradığı 3 kritik niteliği ve ekibinizin bu özelliklere sahip olduğunu ispatlayan hikaye anlatım çerçevesi.",
        duration: "18 dk",
      },
      {
        title: "Kritik Hatalar & Sunum Optimizasyonu",
        desc: "Gerçek yatırım görüşmelerinden derlenen en yaygın sunum hataları ve bunları ortadan kaldıracak slayt-bazlı düzeltme aksiyonları.",
        duration: "31 dk",
      },
    ],
    checkoutTitle: "Yatırımcı Sunumu Eğitimi",
    checkoutNote: "5 Modül · 134 Dakika Tam Erişim",
  },
  freeTrainingPage: {
    badge: "Ücretsiz Video Eğitim",
    titleTop: "Startup'ların Yatırımcı Karşısında Yaptığı",
    titleBottom: "7 Ölümcül Hata",
    intro:
      "Yatırım görüşmelerinin %90'ı ilk 4 dakikada kaybedilir. Bu pratik sunumda, Eser Memişoğlu'nun 10 yıllık tecrübesiyle derlediği ve yatırımcıların anında 'Red' vermesine sebep olan hataları örneklerle öğreneceksiniz.",
    features: [
      "Sunum slaytlarında yapılan en büyük yapısal hatalar",
      "Doğru pazar büyüklüğü (TAM, SAM, SOM) hesaplama yöntemi",
      "Yatırımcının duymak istediği kritik finansal büyüme dili",
      "AI entegrasyonu ve ölçeklenme stratejisi vaatleri",
    ],
    formTitle: "Eğitime Hemen Katılın",
    formLead: "Eğitimi izlemek için aşağıdaki formu doldurmanız yeterlidir.",
    namePlaceholder: "Adınız Soyadınız",
    emailPlaceholder: "E-posta Adresiniz",
    phonePlaceholder: "Telefon Numaranız (WhatsApp)",
    companyPlaceholder: "Şirket / Proje Adı",
    stages: {
      idea: "Fikir Aşaması (Idea)",
      mvp: "Prototip / MVP",
      preSeed: "İlk Satışlar (Pre-Seed)",
      seed: "Yatırıma Hazırlık (Seed)",
      growth: "Ölçeklenme (Growth)",
    },
    consent: "Eğitim linkleri, haftalık büyüme tüyoları ve WhatsApp bilgilendirmelerini kabul ediyorum.",
    submitting: "Kaydediliyor...",
    submit: "Eğitimi Kilidini Aç",
    accessGranted: "Erişim Sağlandı",
    videoHeading: "Startup'ların Yatırımcı Karşısında Yaptığı 7 Ölümcül Hata",
    videoTitle: "12 Dakikalık Ücretsiz Startup Eğitimi",
    videoLabel: "Eğitimi Başlat (12 Dakika)",
    posterBadge: "Ücretsiz · 12 Dakika",
    posterTitle: "Yatırımcı Karşısında Yapılan 7 Ölümcül Hata",
    posterSubtitle: "İzlemek için tıkla — kredi kartı gerekmez",
    upsellEyebrow: "BİR SONRAKİ ADIM",
    upsellTitle: "Milyon dolarlık startup kurmanın tüm şifrelerini çözün!",
    upsellBodyBefore: "Check-up, MVP geliştirme, funnel kurulumu ve büyüme otomasyonlarını içeren ",
    upsellBodyStrong: "Hedef Milyon Dolar E-Kitabımızı",
    upsellBodyAfter: " edinin.",
    upsellCta: "E-Kitabı Edin (6 $)",
  },
  thankYouPage: {
    loading: "Yükleniyor...",
    badge: "Ödeme Başarılı",
    titleEbook: "E-Kitabınız Hazır!",
    titleCourse: "Erişiminiz Açıldı!",
    bodyEbook:
      "Hedef Milyon Dolar e-kitabınız başarıyla satın alındı. Aşağıdan indirmeye başlayabilirsiniz. İndirme linki e-posta adresinize de iletildi.",
    bodyCourse:
      "Satın aldığınız eğitime tam erişiminiz açıldı. Öğrenci portalına giriş yaparak izlemeye başlayabilirsiniz.",
    ctaEbook: "E-Kitabı İndir",
    ctaCourse: "Eğitime Başla",
    upsellEyebrow: "%50 İndirim Kazandınız",
    upsellTitle: "Eğitimleri Sana Özel Fiyata Al",
    upsellBodyBefore: "E-kitabı aldığın için tüm video eğitimler senin için ",
    upsellBodyStrong: "%50 indirimli",
    upsellBodyAfter: ". İki seçenek:",
    option1: "Seçenek 1 · Bir eğitim seç",
    option2: "Seçenek 2 · Hepsi birden — en avantajlı",
    bundleNote: "3 eğitimin tamamı",
    bundleCta: "{price} $ · Hepsini Al",
    bundleOldPrice: "210 $",
    noteDiscounted: "Video eğitim · e-kitap alana özel %50",
    consultEyebrow: "Birebir Çalışma Fırsatı",
    consultTitleTop: "Startup Check-Up ile",
    consultTitleBottom: "Büyüme Planınızı Kuralım",
    consultBodyBefore: "Eğitimi tamamlayan girişimcilere özel: Eser Memişoğlu ile birebir ",
    consultBodyStrong: "Startup Check-Up ve Growth Danışmanlığı",
    consultBodyAfter: " seansı için ön kayıt başlatın.",
    consultCta: "Ücretsiz Ön Kayıt Yap",
  },
  portal: {
    notLoggedIn: "Giriş yapılmadı",
    student: "Öğrenci",
    navCourse: "Eğitim İçeriği",
    navEbook: "Dosyalarım",
    backHome: "Ana Sayfaya Dön",
    logout: "Çıkış Yap",

    myTrainings: "Eğitimlerim",
    dashboardEyebrow: "Eğitim Panelim",
    welcome: "Hoş geldin 👋",
    freeBadge: "Ücretsiz",
    freeCardTitle: "12 Dakikalık Ücretsiz Eğitim",
    freeCardDesc: "Yatırımcı karşısında yapılan 7 ölümcül hata.",
    watch: "İzle",
    freeEyebrow: "Ücretsiz Eğitim",
    freeHeading: "Yatırımcı Karşısında Yapılan 7 Ölümcül Hata",
    freeVideoTitle: "12 Dakikalık Ücretsiz Eğitim",
    freeVideoLabel: "Eğitimi Başlat (12 Dakika)",
    freePosterBadge: "Ücretsiz · 12 Dakika",
    previewSuffix: "Tanıtım",
    watchPreview: "Tanıtımı İzle",
    completed: "Tamamlandı",
    markCompleted: "Tamamlandı işaretle",
    sections: "Bölümler",
    progress: "İlerleme",
    continue: "Devam Et",
    startWatching: "İzlemeye Başla",
    ebookCardTitle: "Dosyalarım",
    ebookCardDesc: "Kitabın ve sunum dosyaların burada.",
    otherTrainings: "Diğer Eğitimler",
    trainings: "Eğitimler",
    preview: "Tanıtım",
    buy: "Satın Al",
    discountNote: "E-kitap sahibi olanlar tüm eğitimlerde %50 indirimli ({price} $).",

    owned: "Sahip",
    read: "Oku",
    withEbook: "/ e-kitapla {price} $",
    belgeKitap: "Kitap (dijital sürüm)",
    belgeKitapLead: "Basılı kitabın dijital sürümü — burada, site içinde okuyabilirsin.",
    belgeSunum: "Sunum Dosyaları",
    belgeSunumLead: "Eğitimlerde ders olarak anlattığım sunumun tamamı.",
    belgeHazirlaniyor: "Bu belge hazırlanıyor, çok yakında burada olacak.",
    belgelerBaslik: "Dosyalarım",
    ebookEmptyTitle: "E-kitabın burada görünecek",
    ebookEmptyBodyBefore: "Bu e-posta ile e-kitap satın alımı bulunamadı. Hedef Milyon Dolar e-kitabını ",
    ebookEmptyBodyAfter: "'a edinebilirsin.",
    ebookEmptyCta: "E-Kitabı Al (6 $)",
    ebookTitle: "Hedef Milyon Dolar",
    ebookLead: "Kitabını burada, site içinde okuyabilirsin.",
    ebookFooter: "Erişimin hesabına tanımlı — istediğin zaman buradan okuyabilirsin.",
    ebookError: "E-kitap açılamadı.",
    connectionError: "Bağlantı hatası.",
  },
  ai: {
    greeting:
      "Merhaba! Ben Startup Doktoru AI Mentörü. Girişiminizin fikrini doğrulamak, değerleme hazırlığı yapmak veya büyüme hunileri (funnel) kurmak konusunda size yol göstermeye hazırım.\n\nNasıl bir girişim projesi üzerinde çalışıyorsunuz? Fikrinizi bana kısaca anlatın, hemen analiz edelim.",
    title: "AI Mentor Asistanı",
    subtitle: "Eser Memişoğlu Büyüme & Yatırım Modeli",
    close: "Kapat",
    gateTitle: "Mentöre bağlanmadan önce",
    gateLead:
      "Sana ve projene özel yanıtlar verebilmem için kısa birkaç bilgi. Bilgilerin sadece sana daha iyi yardımcı olmak için kullanılır.",
    namePlaceholder: "Adın Soyadın",
    emailPlaceholder: "E-posta adresin",
    phonePlaceholder: "Telefon (+90 5xx xxx xx xx)",
    projectPlaceholder: "Projenin adı (gerçek ya da takma)",
    gateCta: "Mentörle Konuşmaya Başla",
    gateNote: "Bilgilerin gizli tutulur, üçüncü taraflarla paylaşılmaz.",
    statusBefore: "Mevcut Durum:",
    statusValue: "Girişim Check-Up Bekleniyor",
    raiseScore: "Puan Artır",
    roleUser: "Girişimci",
    roleAssistant: "Dr. Startup AI",
    thinking: "Fikir analizi yapılıyor ve büyüme hunisi planlanıyor...",
    inputPlaceholder: "Girişim projenizi veya takıldığınız konuyu yazın...",
    hata: "Şu anda cevap veremiyorum — mentör servisine ulaşılamıyor. Birazdan tekrar dener misin?",
    disclaimer:
      "Startup Doktoru AI mentorunun yönlendirmeleri yatırım tavsiyesi içermez. \u201CKervan yolda değil, stratejiyle düzülür.\u201D",
  },
  blog: {
    eyebrow: "Blog",
    title: "Girişimcilik Yazıları",
    lead: "Yatırım, değerleme, inovasyon ve büyüme üzerine sahadan, uygulanabilir içerikler.",
    empty: "Henüz yazı yayınlanmadı. Çok yakında.",
    read: "Oku",
    back: "Tüm yazılar",
    notFound: "Yazı bulunamadı — Startup Doktoru",
    draftPrefix: "[TASLAK]",
    draftNoticeStrong: "Taslak önizlemesi.",
    draftNoticeBefore: " Bu yazı yayında değil — site ziyaretçileri göremez, arama motorlarına kapalı. Yayına almak için admin panelindeki ",
    draftNoticeEm: "Yayınla",
    draftNoticeAfter: " düğmesini kullan.",
    ctaLead: "Girişimini bir üst seviyeye taşımaya hazır mısın?",
    cta: "E-Kitabı İncele (6 $)",
    dateLocale: "tr-TR",
  },
  ebookEn: {
    badge: "İngilizce Baskı",
    title: "İngilizce baskı hazırlanıyor",
    lead: "Kitap şu an yalnızca Türkçe. İngilizce baskıyı hazırlıyoruz — çıktığında ilk sen haberdar ol.",
    placeholder: "e-posta adresin",
    cta: "Haber Ver",
    sending: "Gönderiliyor...",
    doneTitle: "Listeye eklendin",
    doneBody: "İngilizce baskı çıktığında sana yazacağız. Bu arada ücretsiz eğitime göz atabilirsin.",
    error: "Kayıt alınamadı, tekrar dener misin?",
    turkishNote: "Türkçe okuyorsan kitabı şimdi alabilirsin.",
    turkishCta: "Türkçe sürüme git",
  },
};

export type Dict = typeof tr;
